version: 2.1

jobs:
  test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{checksum ".circleci/config.yml" }}-{{checksum "package-lock.json"}}
            - node-deps-v1-{{checksum ".circleci/config.yml"}}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
            - /usr/local/lib/node_modules
      - run:
          name: Run Tests
          command: npm test

workflows:
  "password-gen-workflow":
    jobs:
      - test
